package NickSifniotis.SimpleDatabase.Queries;

/**
 * Base class for ORDER and WHERE clause fragments.
 *
 * @author Nick Sifniotis 5809912
 * @since 09/11/2015
 * @version 1.0.0
 *
 */
public abstract class Query
{
    /**
     * @return the SQL generated by this query fragment.
     */
    public abstract String SQL();
}
