package NickSifniotis.SimpleDatabase.Queries;

/**
 * Created by nsifniotis on 9/11/15.
 *
 * Base class for ORDER and WHERE clause fragments.
 *
 */
public abstract class Query
{
    /**
     * Nick Sifniotis u5809912
     * 09/11/2015
     *
     * @return the SQL generated by this query fragment.
     */
    public abstract String SQL();
}
